### PR TITLE
Upgrade to 1.0

### PR DESCRIPTION
**Pull request by fleadope**

### CODE REVIEW

**Comment by d4rky-pl** [comment]
Hi, could you please remove the second commit as it is unrelated to this pull request ?

**Comment by d4rky-pl** [comment]
You can send it over as second pull request as the feature is useful and I'm willing to merge it in

**Comment by d4rky-pl** [comment]
Fixed by #15

**Comment by fleadope** [comment]
Sorry, was on vacation, didn't see until now....

**Pull request closed without merging**
